server:
  port: 8090
debug: true
spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth_route
          uri: ${AUTH_SERVICE_URI:http://localhost:8091}
          predicates:
            - Path=/auth/**
        - id: calory_route
          uri: ${LEDGER_SERVICE_URI:http://localhost:8092}
          predicates:
            - Path=/calapp/**
        - id: product_route
          uri: ${PRODUCT_SERVICE_URI:http://localhost:8093}
          predicates:
            - Path=/product/**

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        delivery.timeout.ms: 20000
        linger.ms: 0
        request.timeout.ms: 10000
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP:ledger-service-consumer}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

#  cloud:
#    gateway:
#      routes:
#        - id: auth_route
#          uri: http://localhost:8091
#          predicates:
#            - Path=/auth/**
#        - id: calapp_route
#          uri: http://localhost:8092
#          predicates:
#            - Path=/calapp/**