server:
  port: 8090
debug: true
spring:
  application:
    name: api-gateway


  kafka:
    bootstrap-servers: 192.168.0.33:9092, 192.168.0.33:9093, 192.168.0.33:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        delivery.timeout.ms: 20000
        linger.ms: 0
        request.timeout.ms: 10000
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
    consumer:
      group-id: ledger-service-consumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

#  cloud:
#    gateway:
#      routes:
#        - id: auth_route
#          uri: http://localhost:8091
#          predicates:
#            - Path=/auth/**
#        - id: calapp_route
#          uri: http://localhost:8092
#          predicates:
#            - Path=/calapp/**