server:
  port: 8090

debug: true

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        # ---------------- Auth Service ----------------
        - id: auth_route
          uri: ${AUTH_SERVICE_URI:http://user-service:8091}
          predicates:
            - Path=/auth/**

        # ---------------- User Details Service ----------------
        - id: userdetails_route
          uri: ${LEDGER_SERVICE_URI:http://calorie-service:8092}
          predicates:
            - Path=/userdetails/**

        # ---------------- Calorie Service ----------------
        - id: calapp_route
          uri: ${LEDGER_SERVICE_URI:http://calorie-service:8092}
          predicates:
            - Path=/calapp/**

        # ---------------- API Connection Service ----------------
        - id: product_route
          uri: ${PRODUCT_SERVICE_URI:http://api-connection-service:8093}
          predicates:
            - Path=/product/**

        # ---------------- FatSecret / FoodSecret Service ----------------
        - id: foodsecret_route
          uri: ${FOODSECRET_SERVICE_URI:http://fatsecret-service:8095}
          predicates:
            - Path=/foodsecret/**

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        delivery.timeout.ms: 20000
        linger.ms: 0
        request.timeout.ms: 10000
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP:ledger-service-consumer}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
