server:
  port: 8095

logging:
  level:
    org:
      springframework:
        security: DEBUG

spring:
  application:
    name: foodsecret-api-connection
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: ${KAFKA_GROUP_ID:food-analysis-group}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  web:
    resources:
      add-mappings: false
fatsecret:
  oauth:
    token-url: ${FATSECRET_TOKEN_URL:https://oauth.fatsecret.com/connect/token}
    client-id: ${FATSECRET_CLIENT_ID}
    client-secret: ${FATSECRET_CLIENT_SECRET}
    scope: ${FATSECRET_SCOPE:basic}
